version: "3.9"
services:
  frontend:
    build: .
    image: ahmedbello/php-todo
    ports:
      - "80:80"
    volumes:
      - frontend:/app
    links:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  frontend:
  db: